language: smalltalk
sudo: false
smalltalk:
  - Pharo-6.0
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0
  - Squeak-5.1
  - Squeak-5.0
  - Squeak-4.6
  - Squeak-4.5
  - GemStone-3.3.0
  - GemStone-3.2.12
  - GemStone-3.1.0.6
cache:
  directories:
    - $SMALLTALK_CI_CACHE
smalltalk_config:
  - .smalltalk-configuration.ston
