language: smalltalk
sudo: false
smalltalk:
  - Pharo-6.1
  - Pharo-6.0
  - Pharo-5.0
  - Pharo-4.0
  - Squeak-5.1
  - GemStone-3.3.4
  - GemStone-3.2.17
  - GemStone-3.1.0.6
cache:
  directories:
    - $SMALLTALK_CI_CACHE
